### ISSUE TITLE
ValueError: No gradients provided for any variable

### ISSUE THREAD

**Issue by XuyangPan** [prasunroy/stefann#15]
Hello, prasunroy. Thank you for the amazing work. I tried to train fannet by `python stefann/fannet.py` following your codes, but got `ValueError: No gradients provided for any variable` and it stopped training.
Could you give me a solution to fix the bug？

![1618383906(1)](https://user-images.githubusercontent.com/39898699/114668551-76fb3680-9d33-11eb-8066-66958b0667b1.jpg)

**Comment by prasunroy** [comment]
Hi @XuyangPan, I tried to reproduce the issue but for me it's working without any problem. I guess you are getting the error due to some breaking changes in the latest version of Keras / TensorFlow. The tested versions of various dependencies are mentioned in the [README](https://github.com/prasunroy/stefann#1-installing-dependencies). I would recommend you to use the supplied configuration files to create a new environment as mentioned [here](https://github.com/prasunroy/stefann#step-4-create-an-environment-and-install-depenpencies).

**Comment by XuyangPan** [comment]
ok， I got it. The bug was fixed.
Thanks
