### ISSUE TITLE
Making word longer?

### ISSUE THREAD

**Issue by dietercastel** [prasunroy/stefann#9]
Now I'm playing around with Stefann a bit. Your [readme](https://github.com/prasunroy/stefann/blob/master/release/readme.html) was really helpful here! But I guess there's more knobs and dials to it than I expected. Was still wondering is there e.g. a way to make the word you're replacing longer? Also, your examples seem way more crips than my quick shot at it. Got any tips?

Original:
![backspace orig](https://user-images.githubusercontent.com/2487783/90815259-b4393100-e32a-11ea-80d6-192b58bd8d9e.jpg)
Edited
![backspace-button_2020-08-20-21-15-52](https://user-images.githubusercontent.com/2487783/90815382-e77bc000-e32a-11ea-8f33-c7301550daf3.jpg)

**Comment by prasunroy** [comment]
### About string length
In our demo, the length of the input cannot be changed out of the box. Sorry! However, this feature is essentially GUI specific and it can be implemented by rewriting parts of [stefann.py](https://github.com/prasunroy/stefann/blob/master/release/stefann.py). Unfortunately, it would be quite a bit of work.

### About visual quality
Your observation is correct. The released model for FANnet was trained only on uppercase letters. Most of the results shown in the paper involve uppercase letters as well. While it is possible to train a model on lowercase letters easily, we did not include it in final release. Because for uppercase letters, every letter has equal height, but for lowercase letters, individual letters can span across diferent zones (upper / middle / lower). This further complicates the target letter placement.

The aim of the paper was to propose a pipeline to address a potentially useful problem (scene text editing) and to show the feasibility and applicability of such a pipeline. At present, there are many limitations exist in STEFANN. The most common issue is unstable generation due to inadequate domain adaptation. STEFANN follows a supervised learning approach with source and target image pairs. It is extremely difficult to prepare such a dataset from scene text images. Thus, STEFANN was trained using synthetic data (Google Fonts). During inference, the quality of generation is heavily affected by noisy artifacts in segmentation stage. It takes some manual efforts to find best possible thresholds during segmentation. Even then **_not every image produces visually crisp result_**.

#### Here are few random examples along with respective tweaks:
| Original & Edited Images | Inverse Binarization | Binarization Threshold | Minimum Allowed Contour Area |
| :---: | :---: | :---: | :---: |
| ![0_180_10](https://user-images.githubusercontent.com/38404108/90964790-50a53400-e4e1-11ea-85c3-c717bf187270.jpg) | No | 180 | 10 |
| ![0_165_20](https://user-images.githubusercontent.com/38404108/90965016-f6f13980-e4e1-11ea-9ce0-051b2ce50a78.jpg) | No | 165 | 20 |
| ![1_110_25](https://user-images.githubusercontent.com/38404108/90965039-2a33c880-e4e2-11ea-90c1-5c4efb21a872.jpg) | Yes | 110 | 25 |
| ![0_110_10](https://user-images.githubusercontent.com/38404108/90965049-46d00080-e4e2-11ea-8604-c17f2a44e335.jpg) | No | 110 | 10 |

>Check out [this video](https://www.youtube.com/watch?v=HBOt9Hb__AY) for more examples using the [sample images](https://drive.google.com/uc?export=download&id=1Gzb-VYeQJNXwDnkoEI4iAskOGYmWR6Rk).

**Comment by dietercastel** [comment]
# About string length
Okay, I'm glad it's not required to retrain the network in full for this. Some GUI coding in python is certainly doable! If I get around doing this I'll definitely contribute upstream. :-)

Could you be more specific what code I should look at? Because I'm not yet familiar with  the source code some pointers might help. :-)

# About visual quality

I see. I took a, signal/noise large, example so the details are of course more visually striking. But it's good to know what the limitations are of the network.

As a workaround maybe there exists a capitalisation NN. That would probably help solve this.

**Comment by dietercastel** [comment]
For visual quality I also noticed that deskewing helps a lot.

![deskew_blue_bs_2020-08-24-21-03-52](https://user-images.githubusercontent.com/2487783/91085302-8830ef00-e64d-11ea-98fb-fba3ce396d9c.png)

I did deskewing with this handy [deskew tool available on pip/github](https://github.com/sbrunner/deskew). It might be helpful to integrate this feature into stefann.
